/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralProblem } from './GeneralProblem';
import {
    GeneralProblemFromJSON,
    GeneralProblemFromJSONTyped,
    GeneralProblemToJSON,
    GeneralProblemToJSONTyped,
} from './GeneralProblem';

/**
 * The request is invalid and cannot be processed. Typical payload 400 Bad Request Code
 * @export
 * @interface BadRequestProblem
 */
export interface BadRequestProblem extends GeneralProblem {
    /**
     * 
     */
    type: string;
    /**
     * 
     */
    oasDiscriminator: string;
}



/**
 * Check if a given object implements the BadRequestProblem interface.
 */
export function instanceOfBadRequestProblem(value: object): value is BadRequestProblem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('oasDiscriminator' in value) || value['oasDiscriminator'] === undefined) return false;
    return true;
}

export function BadRequestProblemFromJSON(json: any): BadRequestProblem {
    return BadRequestProblemFromJSONTyped(json, false);
}

export function BadRequestProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequestProblem {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {

    }
    return {
        ...GeneralProblemFromJSONTyped(json, true),
        'type': json['type'],
        'oasDiscriminator': json['oasDiscriminator'],
    };
}

export function BadRequestProblemToJSON(json: any): BadRequestProblem {
    return BadRequestProblemToJSONTyped(json, false);
}

export function BadRequestProblemToJSONTyped(value?: BadRequestProblem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['oasDiscriminator']) {
            default:
                return value;
        }
    }

    return {
        ...GeneralProblemToJSONTyped(value, true),
        'type': value['type'],
        'oasDiscriminator': value['oasDiscriminator'],
    };
}

