/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The hour and the labels to associate with it.
 * @export
 * @interface CreateTimeSlotOptionRequestDto
 */
export interface CreateTimeSlotOptionRequestDto {
    /**
     * 
     */
    hour: number;
    /**
     * 
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the CreateTimeSlotOptionRequestDto interface.
 */
export function instanceOfCreateTimeSlotOptionRequestDto(value: object): value is CreateTimeSlotOptionRequestDto {
    if (!('hour' in value) || value['hour'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function CreateTimeSlotOptionRequestDtoFromJSON(json: any): CreateTimeSlotOptionRequestDto {
    return CreateTimeSlotOptionRequestDtoFromJSONTyped(json, false);
}

export function CreateTimeSlotOptionRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTimeSlotOptionRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hour': json['hour'],
        'labels': json['labels'],
    };
}

export function CreateTimeSlotOptionRequestDtoToJSON(json: any): CreateTimeSlotOptionRequestDto {
    return CreateTimeSlotOptionRequestDtoToJSONTyped(json, false);
}

export function CreateTimeSlotOptionRequestDtoToJSONTyped(value?: CreateTimeSlotOptionRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hour': value['hour'],
        'labels': value['labels'],
    };
}

