/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * The details of the invitation to create
 * @export
 * @interface DateInvitationCreateRequestDto
 */
export interface DateInvitationCreateRequestDto {
    /**
     * 
     */
    scheduledTime: Date;
    /**
     * 
     */
    label: string;
    /**
     * 
     */
    recipientEmail: string;
}

/**
 * Check if a given object implements the DateInvitationCreateRequestDto interface.
 */
export function instanceOfDateInvitationCreateRequestDto(value: object): value is DateInvitationCreateRequestDto {
    if (!('scheduledTime' in value) || value['scheduledTime'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('recipientEmail' in value) || value['recipientEmail'] === undefined) return false;
    return true;
}

export function DateInvitationCreateRequestDtoFromJSON(json: any): DateInvitationCreateRequestDto {
    return DateInvitationCreateRequestDtoFromJSONTyped(json, false);
}

export function DateInvitationCreateRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateInvitationCreateRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduledTime': (json['scheduledTime'] == null ? json['scheduledTime'] : parseDateTime(json['scheduledTime'])),
        'label': json['label'],
        'recipientEmail': json['recipientEmail'],
    };
}

export function DateInvitationCreateRequestDtoToJSON(json: any): DateInvitationCreateRequestDto {
    return DateInvitationCreateRequestDtoToJSONTyped(json, false);
}

export function DateInvitationCreateRequestDtoToJSONTyped(value?: DateInvitationCreateRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scheduledTime': value['scheduledTime'] == null ? value['scheduledTime'] : serializeDateTime(value['scheduledTime']),
        'label': value['label'],
        'recipientEmail': value['recipientEmail'],
    };
}

