/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralProblem } from './GeneralProblem';
import {
    GeneralProblemFromJSON,
    GeneralProblemFromJSONTyped,
    GeneralProblemToJSON,
    GeneralProblemToJSONTyped,
} from './GeneralProblem';

/**
 * The client is authenticated but cannot execute the operation. Typical payload for the 403 Forbidden status code. 
 * @export
 * @interface ForbiddenProblem
 */
export interface ForbiddenProblem extends GeneralProblem {
    /**
     * 
     */
    type: string;
    /**
     * HTTP status code
     */
    status: number;
}



/**
 * Check if a given object implements the ForbiddenProblem interface.
 */
export function instanceOfForbiddenProblem(value: object): value is ForbiddenProblem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ForbiddenProblemFromJSON(json: any): ForbiddenProblem {
    return ForbiddenProblemFromJSONTyped(json, false);
}

export function ForbiddenProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenProblem {
    if (json == null) {
        return json;
    }
    return {
        ...GeneralProblemFromJSONTyped(json, true),
        'type': json['type'],
        'status': json['status'],
    };
}

export function ForbiddenProblemToJSON(json: any): ForbiddenProblem {
    return ForbiddenProblemToJSONTyped(json, false);
}

export function ForbiddenProblemToJSONTyped(value?: ForbiddenProblem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...GeneralProblemToJSONTyped(value, true),
        'type': value['type'],
        'status': value['status'],
    };
}

