/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import { type BadRequestProblem, BadRequestProblemFromJSONTyped, BadRequestProblemToJSON, BadRequestProblemToJSONTyped } from './BadRequestProblem';
import { type ForbiddenProblem, ForbiddenProblemFromJSONTyped, ForbiddenProblemToJSON, ForbiddenProblemToJSONTyped } from './ForbiddenProblem';
import { type NotFoundProblem, NotFoundProblemFromJSONTyped, NotFoundProblemToJSON, NotFoundProblemToJSONTyped } from './NotFoundProblem';
import { type UnauthorizedProblem, UnauthorizedProblemFromJSONTyped, UnauthorizedProblemToJSON, UnauthorizedProblemToJSONTyped } from './UnauthorizedProblem';
/**
 * A general problem that can be used as base for more specific problems.
 * @export
 * @interface GeneralProblem
 */
export interface GeneralProblem {
    /**
     * Unique identifier of the error. The change to it, is considered a breaking change in the API
     */
    type: string;
    /**
     * Error ID as described on...
     */
    errorId: string;
    /**
     * Minimalistic and short description of the error to get the idea of the context.
     */
    title: string;
    /**
     * HTTP status code
     */
    status: number;
    /**
     * A human readable and localized error message shown to the user.
     */
    detail: string;
    /**
     * 
     */
    severity: GeneralProblemSeverityEnum;
    /**
     * Trace ID to be able to find relevant log entries
     */
    traceId?: string;
    /**
     * 
     */
    timestamp: Date;
    /**
     * 
     */
    oasDiscriminator: string;
}


/**
 * @export
 */
export const GeneralProblemSeverityEnum = {
    Critical: 'Critical',
    High: 'High',
    Moderate: 'Moderate',
    Low: 'Low',
    UnknownDefaultOpenApi: 'unknown_default_open_api',
} as const;
export type GeneralProblemSeverityEnum = typeof GeneralProblemSeverityEnum[keyof typeof GeneralProblemSeverityEnum];


/**
 * Check if a given object implements the GeneralProblem interface.
 */
export function instanceOfGeneralProblem(value: object): value is GeneralProblem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('errorId' in value) || value['errorId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('oasDiscriminator' in value) || value['oasDiscriminator'] === undefined) return false;
    return true;
}

export function GeneralProblemFromJSON(json: any): GeneralProblem {
    return GeneralProblemFromJSONTyped(json, false);
}

export function GeneralProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralProblem {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['oasDiscriminator'] === 'BadRequestProblem') {
            return BadRequestProblemFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['oasDiscriminator'] === 'ForbiddenProblem') {
            return ForbiddenProblemFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['oasDiscriminator'] === 'NotFoundProblem') {
            return NotFoundProblemFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['oasDiscriminator'] === 'UnauthorizedProblem') {
            return UnauthorizedProblemFromJSONTyped(json, ignoreDiscriminator);
        }

    }
    return {
        
        'type': json['type'],
        'errorId': json['errorId'],
        'title': json['title'],
        'status': json['status'],
        'detail': json['detail'],
        'severity': json['severity'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
        'timestamp': (json['timestamp'] == null ? json['timestamp'] : parseDateTime(json['timestamp'])),
        'oasDiscriminator': json['oasDiscriminator'],
    };
}

export function GeneralProblemToJSON(json: any): GeneralProblem {
    return GeneralProblemToJSONTyped(json, false);
}

export function GeneralProblemToJSONTyped(value?: GeneralProblem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['oasDiscriminator']) {
            case 'BadRequestProblem':
                return BadRequestProblemToJSONTyped(value as BadRequestProblem, ignoreDiscriminator);
            case 'ForbiddenProblem':
                return ForbiddenProblemToJSONTyped(value as ForbiddenProblem, ignoreDiscriminator);
            case 'NotFoundProblem':
                return NotFoundProblemToJSONTyped(value as NotFoundProblem, ignoreDiscriminator);
            case 'UnauthorizedProblem':
                return UnauthorizedProblemToJSONTyped(value as UnauthorizedProblem, ignoreDiscriminator);
            default:
                return value;
        }
    }

    return {
        
        'type': value['type'],
        'errorId': value['errorId'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'severity': value['severity'],
        'traceId': value['traceId'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : serializeDateTime(value['timestamp']),
        'oasDiscriminator': value['oasDiscriminator'],
    };
}

