/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralProblem } from './GeneralProblem';
import {
    GeneralProblemFromJSON,
    GeneralProblemFromJSONTyped,
    GeneralProblemToJSON,
    GeneralProblemToJSONTyped,
} from './GeneralProblem';

/**
 * The requested source cannot be found. Typical payload 404 Not Found Code
 * @export
 * @interface NotFoundProblem
 */
export interface NotFoundProblem extends GeneralProblem {
    /**
     * 
     */
    type: string;
    /**
     * 
     */
    status: number;
}



/**
 * Check if a given object implements the NotFoundProblem interface.
 */
export function instanceOfNotFoundProblem(value: object): value is NotFoundProblem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NotFoundProblemFromJSON(json: any): NotFoundProblem {
    return NotFoundProblemFromJSONTyped(json, false);
}

export function NotFoundProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundProblem {
    if (json == null) {
        return json;
    }
    return {
        ...GeneralProblemFromJSONTyped(json, true),
        'type': json['type'],
        'status': json['status'],
    };
}

export function NotFoundProblemToJSON(json: any): NotFoundProblem {
    return NotFoundProblemToJSONTyped(json, false);
}

export function NotFoundProblemToJSONTyped(value?: NotFoundProblem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...GeneralProblemToJSONTyped(value, true),
        'type': value['type'],
        'status': value['status'],
    };
}

