/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSlotResponseDto
 */
export interface TimeSlotResponseDto {
    /**
     * 
     */
    hour: number;
    /**
     * 
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the TimeSlotResponseDto interface.
 */
export function instanceOfTimeSlotResponseDto(value: object): value is TimeSlotResponseDto {
    if (!('hour' in value) || value['hour'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function TimeSlotResponseDtoFromJSON(json: any): TimeSlotResponseDto {
    return TimeSlotResponseDtoFromJSONTyped(json, false);
}

export function TimeSlotResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlotResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hour': json['hour'],
        'labels': json['labels'],
    };
}

export function TimeSlotResponseDtoToJSON(json: any): TimeSlotResponseDto {
    return TimeSlotResponseDtoToJSONTyped(json, false);
}

export function TimeSlotResponseDtoToJSONTyped(value?: TimeSlotResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hour': value['hour'],
        'labels': value['labels'],
    };
}

