/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralProblem } from './GeneralProblem';
import {
    GeneralProblemFromJSON,
    GeneralProblemFromJSONTyped,
    GeneralProblemToJSON,
    GeneralProblemToJSONTyped,
} from './GeneralProblem';

/**
 * The client is not authenticated and needs to authenticate to get the needed permissions. Typical payload for the 401 Unauthorized status code. 
 * @export
 * @interface UnauthorizedProblem
 */
export interface UnauthorizedProblem extends GeneralProblem {
    /**
     * 
     */
    type: string;
    /**
     * HTTP status code
     */
    status: number;
}



/**
 * Check if a given object implements the UnauthorizedProblem interface.
 */
export function instanceOfUnauthorizedProblem(value: object): value is UnauthorizedProblem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UnauthorizedProblemFromJSON(json: any): UnauthorizedProblem {
    return UnauthorizedProblemFromJSONTyped(json, false);
}

export function UnauthorizedProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedProblem {
    if (json == null) {
        return json;
    }
    return {
        ...GeneralProblemFromJSONTyped(json, true),
        'type': json['type'],
        'status': json['status'],
    };
}

export function UnauthorizedProblemToJSON(json: any): UnauthorizedProblem {
    return UnauthorizedProblemToJSONTyped(json, false);
}

export function UnauthorizedProblemToJSONTyped(value?: UnauthorizedProblem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...GeneralProblemToJSONTyped(value, true),
        'type': value['type'],
        'status': value['status'],
    };
}

