/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestProblem,
    BadRequestProblemFromJSON,
    BadRequestProblemToJSON,
} from '../models/BadRequestProblem';
import {
    type DateInvitationCreateRequestDto,
    DateInvitationCreateRequestDtoFromJSON,
    DateInvitationCreateRequestDtoToJSON,
} from '../models/DateInvitationCreateRequestDto';
import {
    type ForbiddenProblem,
    ForbiddenProblemFromJSON,
    ForbiddenProblemToJSON,
} from '../models/ForbiddenProblem';
import {
    type GeneralProblem,
    GeneralProblemFromJSON,
    GeneralProblemToJSON,
} from '../models/GeneralProblem';
import {
    type UnauthorizedProblem,
    UnauthorizedProblemFromJSON,
    UnauthorizedProblemToJSON,
} from '../models/UnauthorizedProblem';

export interface ScheduleDateV1Request {
    /**
     * 
     */
    dateInvitationCreateRequestDto: DateInvitationCreateRequestDto;
}

/**
 * 
 */
export class DateInvitationV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for scheduleDateV1 without sending the request
     */
    async scheduleDateV1RequestOpts(requestParameters: ScheduleDateV1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['dateInvitationCreateRequestDto'] == null) {
            throw new runtime.RequiredError(
                'dateInvitationCreateRequestDto',
                'Required parameter "dateInvitationCreateRequestDto" was null or undefined when calling scheduleDateV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("meetoraOAuth", []);
        }


        let urlPath = `/v1/invitations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DateInvitationCreateRequestDtoToJSON(requestParameters['dateInvitationCreateRequestDto']),
        };
    }

    /**
     * Creates a new invitation with the provided details.
     * Submit a scheduled date invitation
     */
    async scheduleDateV1Raw(requestParameters: ScheduleDateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.scheduleDateV1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new invitation with the provided details.
     * Submit a scheduled date invitation
     */
    async scheduleDateV1(requestParameters: ScheduleDateV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.scheduleDateV1Raw(requestParameters, initOverrides);
    }

}
