/* tslint:disable */
/* eslint-disable */
/**
 * Meetora Backend
 * Backend for the Meetora date invitation platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestProblem,
    BadRequestProblemFromJSON,
    BadRequestProblemToJSON,
} from '../models/BadRequestProblem';
import {
    type CreateTimeSlotOptionRequestDto,
    CreateTimeSlotOptionRequestDtoFromJSON,
    CreateTimeSlotOptionRequestDtoToJSON,
} from '../models/CreateTimeSlotOptionRequestDto';
import {
    type ForbiddenProblem,
    ForbiddenProblemFromJSON,
    ForbiddenProblemToJSON,
} from '../models/ForbiddenProblem';
import {
    type GeneralProblem,
    GeneralProblemFromJSON,
    GeneralProblemToJSON,
} from '../models/GeneralProblem';
import {
    type NotFoundProblem,
    NotFoundProblemFromJSON,
    NotFoundProblemToJSON,
} from '../models/NotFoundProblem';
import {
    type TimeSlotResponseDto,
    TimeSlotResponseDtoFromJSON,
    TimeSlotResponseDtoToJSON,
} from '../models/TimeSlotResponseDto';
import {
    type UnauthorizedProblem,
    UnauthorizedProblemFromJSON,
    UnauthorizedProblemToJSON,
} from '../models/UnauthorizedProblem';

export interface CreateTimeOptionV1Request {
    /**
     * 
     */
    createTimeSlotOptionRequestDto: CreateTimeSlotOptionRequestDto;
}

/**
 * 
 */
export class TimeSlotV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for createTimeOptionV1 without sending the request
     */
    async createTimeOptionV1RequestOpts(requestParameters: CreateTimeOptionV1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['createTimeSlotOptionRequestDto'] == null) {
            throw new runtime.RequiredError(
                'createTimeSlotOptionRequestDto',
                'Required parameter "createTimeSlotOptionRequestDto" was null or undefined when calling createTimeOptionV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("meetoraOAuth", []);
        }


        let urlPath = `/v1/time-options`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTimeSlotOptionRequestDtoToJSON(requestParameters['createTimeSlotOptionRequestDto']),
        };
    }

    /**
     * Creates a new time slot option with the provided hour and label.
     * Create a new time slot option
     */
    async createTimeOptionV1Raw(requestParameters: CreateTimeOptionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlotResponseDto>> {
        const requestOptions = await this.createTimeOptionV1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a new time slot option with the provided hour and label.
     * Create a new time slot option
     */
    async createTimeOptionV1(requestParameters: CreateTimeOptionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlotResponseDto> {
        const response = await this.createTimeOptionV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTimeOptionsV1 without sending the request
     */
    async getTimeOptionsV1RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("meetoraOAuth", []);
        }


        let urlPath = `/v1/time-options`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a list of available time slot options.
     * Retrieve available time slot options
     */
    async getTimeOptionsV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlotResponseDto>>> {
        const requestOptions = await this.getTimeOptionsV1RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSlotResponseDtoFromJSON));
    }

    /**
     * Retrieves a list of available time slot options.
     * Retrieve available time slot options
     */
    async getTimeOptionsV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlotResponseDto>> {
        const response = await this.getTimeOptionsV1Raw(initOverrides);
        return await response.value();
    }

}
